export const images = {
  Backbtn: require('../../assets/back_arrow.png'),
  uploadpin: require('../../assets/uploadpin.png'),
  InputEmailicon: require('../../assets/mail.png'),
  InputPassIcon: require('../../assets/padlock.png'),
  googleIcon: require('../../assets/googleLogo.png'),
  AppleIcon: require('../../assets/apple.png'),
  Profileimage: require('../../assets/profile.png'),
  Visa: require('../../assets/visa.png'),
  opencemra: require('../../assets/insert.png'),
  EmailLogo: require('../../assets/EmailPicture.png'),
  Cancillogo: require('../../assets/Cancil.png'),
  Greytick: require('../../assets/greytick.png'),
  redtick: require('../../assets/redtick.png'),
  paycashlogo: require('../../assets/paycash.png'),
  paywithVenmo: require('../../assets/paywithvenmo.png'),
  Background: require('../../assets/background.jpg'),
  ThumbsUp: require('../../assets/rating.png'),
  bellIcon: require('../.././assets/bell.png'),
  SearchIcon: require('../.././assets/search.png'),
  logoplusbtn: require('../.././assets/logoplusbtn.png'),
};
